config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  if !Docuseal.multitenant? && defined?(Sidekiq::Web)
    authenticated :user, ->(u) { u.sidekiq? } do
      mount Sidekiq::Web => '/jobs'
    end
  end

  root 'dashboard#index'

  get 'up' => 'rails/health#show'
  get 'manifest' => 'pwa#manifest'

  devise_for :users,
             path: '/', only: %i[sessions passwords omniauth_callbacks],
             controllers: begin
               options = { sessions: 'sessions', passwords: 'passwords' }
               options[:omniauth_callbacks] = 'omniauth_callbacks' if User.devise_modules.include?(:omniauthable)
               options
             end

  devise_scope :user do
    resource :invitation, only: %i[update] do
      get '' => :edit
    end
  end

  namespace :api, defaults: { format: :json } do
    resource :user, only: %i[show]
    resources :attachments, only: %i[create]
    resources :submitter_email_clicks, only: %i[create]
    resources :submitter_form_views, only: %i[create]
    resources :submitters, only: %i[index show update]
    resources :submissions, only: %i[index show create destroy] do
      resources :documents, only: %i[index], controller: 'submission_documents'
      collection do
        resources :init, only: %i[create], controller: 'submissions'
        resources :emails, only: %i[create], controller: 'submissions', as: :submissions_emails
      end
    end
    resources :templates, only: %i[update show index destroy] do
      resources :clone, only: %i[create], controller: 'templates_clone'
      resources :submissions, only: %i[index create]
    end
    resources :tools, only: %i[] do
      post :merge, on: :collection
      post :verify, on: :collection
    end
    scope 'events' do
      resources :form_events, only: %i[index], path: 'form/:type'
      resources :submission_events, only: %i[index], path: 'submission/:type'
    end
  end

  resources :verify_pdf_signature, only: %i[create]
  resource :mfa_setup, only: %i[show new edit create destroy], controller: 'mfa_setup'
  resources :account_configs, only: %i[create destroy]
  resources :user_configs, only: %i[create]
  resources :encrypted_user_configs, only: %i[destroy]
  resources :timestamp_server, only: %i[create]
  resources :dashboard, only: %i[index]
  resources :setup, only: %i[index create]
  resource :newsletter, only: %i[show update]
  resources :enquiries, only: %i[create]
  resources :users, only: %i[new create edit update destroy] do
    resource :send_reset_password, only: %i[update], controller: 'users_send_reset_password'
  end
  resource :user_signature, only: %i[edit update destroy]
  resource :user_initials, only: %i[edit update destroy]
  resources :submissions_archived, only: %i[index], path: 'submissions/archived'
  resources :submissions, only: %i[index], controller: 'submissions_dashboard'
  resources :submissions, only: %i[show destroy] do
    resources :unarchive, only: %i[create], controller: 'submissions_unarchive'
    resources :events, only: %i[index], controller: 'submission_events'
  end
  resources :submitters, only: %i[edit update]
  resources :console_redirect, only: %i[index]
  resources :upgrade, only: %i[index], controller: 'console_redirect'
  resources :manage, only: %i[index], controller: 'console_redirect'
  resource :testing_account, only: %i[show destroy]
  resources :testing_api_settings, only: %i[index]
  resources :submitters_autocomplete, only: %i[index]
  resources :submitters_resubmit, only: %i[update]
  resources :template_folders_autocomplete, only: %i[index]
  resources :webhook_secret, only: %i[show update]
  resources :webhook_preferences, only: %i[update]
  resource :templates_upload, only: %i[create]
  authenticated do
    resource :templates_upload, only: %i[show], path: 'new'
  end
  resources :templates_archived, only: %i[index], path: 'templates/archived'
  resources :folders, only: %i[show edit update destroy], controller: 'template_folders'
  resources :template_sharings_testing, only: %i[create]
  resources :templates, only: %i[index], controller: 'templates_dashboard'
  resources :submissions_filters, only: %i[show], param: 'name'
  resources :templates, only: %i[new create edit update show destroy] do
    resource :debug, only: %i[show], controller: 'templates_debug' if Rails.env.development?
    resources :documents, only: %i[create], controller: 'template_documents'
    resources :clone_and_replace, only: %i[create], controller: 'templates_clone_and_replace'
    resources :restore, only: %i[create], controller: 'templates_restore'
    resources :archived, only: %i[index], controller: 'templates_archived_submissions'
    resources :submissions, only: %i[new create]
    resource :folder, only: %i[edit update], controller: 'templates_folders'
    resource :preview, only: %i[show], controller: 'templates_preview'
    resource :form, only: %i[show], controller: 'templates_form_preview'
    resource :code_modal, only: %i[show], controller: 'templates_code_modal'
    resource :preferences, only: %i[show create], controller: 'templates_preferences'
    resource :share_link, only: %i[show create], controller: 'templates_share_link'
    resources :recipients, only: %i[create], controller: 'templates_recipients'
    resources :prefillable_fields, only: %i[create], controller: 'templates_prefillable_fields'
    resources :submissions_export, only: %i[index new]
  end
  resources :preview_document_page, only: %i[show], path: '/preview/:signed_uuid'
  resource :blobs_proxy, only: %i[show], path: '/file/:signed_uuid/*filename',
                         controller: 'api/active_storage_blobs_proxy'
  resource :blobs_proxy, only: %i[show], path: '/blobs_proxy/:signed_uuid/*filename',
                         controller: 'api/active_storage_blobs_proxy'

  if Docuseal.multitenant?
    resource :blobs_proxy_legacy, only: %i[show],
                                  path: '/blobs/proxy/:signed_id/*filename',
                                  controller: 'api/active_storage_blobs_proxy_legacy',
                                  as: :rails_blob
    get '/disk/:encoded_key/*filename' => 'active_storage/disk#show', as: :rails_disk_service
    put '/disk/:encoded_token' => 'active_storage/disk#update', as: :update_rails_disk_service
    post '/direct_uploads' => 'active_storage/direct_uploads#create', as: :rails_direct_uploads

    ActiveSupport.run_load_hooks(:multitenant_routes, self)
  end

  resources :start_form, only: %i[show update], path: 'd', param: 'slug' do
    get :completed
  end

  resource :resubmit_form, controller: 'start_form', only: :update
  resources :start_form_email_2fa_send, only: :create

  resources :submit_form, only: %i[], path: '' do
    get :success, on: :collection
  end

  resources :submit_form, only: %i[show update], path: 's', param: 'slug' do
    resources :values, only: %i[index], controller: 'submit_form_values'
    resources :download, only: %i[index], controller: 'submit_form_download'
    resources :decline, only: %i[create], controller: 'submit_form_decline'
    resources :invite, only: %i[create], controller: 'submit_form_invite'
    get :completed
  end

  resources :submit_form_draw_signature, only: %i[show], path: 'p', param: 'slug'

  resources :submissions_preview, only: %i[show], path: 'e', param: 'slug' do
    get :completed
  end

  resources :send_submission_email, only: %i[create]

  resources :submitters, only: %i[], param: 'slug' do
    resources :download, only: %i[index], controller: 'submissions_download'
    resources :send_email, only: %i[create], controller: 'submitters_send_email'
    resources :send_sms, only: %i[create], controller: 'submitters_send_sms'
    resources :debug, only: %i[index], controller: 'submissions_debug' if Rails.env.development?
  end

  scope '/settings', as: :settings do
    unless Docuseal.multitenant?
      resources :storage, only: %i[index create], controller: 'storage_settings'
      resources :search_entries_reindex, only: %i[create]
      resources :sms, only: %i[index create], controller: 'sms_settings'
    end
    if Docuseal.demo? || !Docuseal.multitenant?
      resources :api, only: %i[index create], controller: 'api_settings'
      resource :reveal_access_token, only: %i[show create], controller: 'reveal_access_token'
    end
    resources :email, only: %i[index create], controller: 'email_smtp_settings'
    resources :sso, only: %i[index], controller: 'sso_settings'
    resources :notifications, only: %i[index create], controller: 'notifications_settings'
    resource :esign, only: %i[show create new update destroy], controller: 'esign_settings'
    resources :users, only: %i[index]
    resources :archived_users, only: %i[index], path: 'users/:status', controller: 'users',
                               defaults: { status: :archived }
    resources :integration_users, only: %i[index], path: 'users/:status', controller: 'users',
                                  defaults: { status: :integration }
    resource :personalization, only: %i[show create], controller: 'personalization_settings'
    resources :webhooks, only: %i[index show new create update destroy], controller: 'webhook_settings' do
      post :resend

      resources :events, only: %i[show], controller: 'webhook_events' do
        post :resend, on: :member
        post :refresh, on: :member
      end
    end
    resource :account, only: %i[show update destroy]
    resources :profile, only: %i[index] do
      collection do
        patch :update_contact
        patch :update_password
        patch :update_app_url
      end
    end
  end

  get '/js/:filename', to: 'embed_scripts#show', as: :embed_script

  ActiveSupport.run_load_hooks(:routes, self)
end

app/models/webhook_event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: webhook_events
#
#  id             :bigint           not null, primary key
#  event_type     :string           not null
#  record_type    :string           not null
#  status         :string           not null
#  uuid           :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  account_id     :bigint           not null
#  record_id      :bigint           not null
#  webhook_url_id :bigint           not null
#
# Indexes
#
#  index_webhook_events_error                       (webhook_url_id,id) WHERE ((status)::text = 'error'::text)
#  index_webhook_events_on_uuid_and_webhook_url_id  (uuid,webhook_url_id) UNIQUE
#  index_webhook_events_on_webhook_url_id_and_id    (webhook_url_id,id)
#
class WebhookEvent < ApplicationRecord
  attribute :uuid, :string, default: -> { SecureRandom.uuid }

  belongs_to :webhook_url, optional: true
  belongs_to :account, optional: true
  belongs_to :record, polymorphic: true, optional: true

  has_many :webhook_attempts, dependent: nil
end

app/controllers/webhook_events_controller.rb
# frozen_string_literal: true

class WebhookEventsController < ApplicationController
  load_and_authorize_resource :webhook_url, parent: false, id_param: :webhook_id
  before_action :load_webhook_event

  def show
    return unless current_ability.can?(:read, @webhook_event.record)

    @data =
      case @webhook_event.event_type
      when 'form.started', 'form.completed', 'form.declined', 'form.viewed'
        Submitters::SerializeForWebhook.call(@webhook_event.record)
      when 'submission.created', 'submission.completed', 'submission.expired'
        Submissions::SerializeForApi.call(@webhook_event.record)
      when 'template.created', 'template.updated'
        Templates::SerializeForApi.call(@webhook_event.record)
      when 'submission.archived'
        @webhook_event.record.as_json(only: %i[id archived_at])
      end
  end

  def resend
    id_key = WebhookUrls::EVENT_TYPE_ID_KEYS.fetch(@webhook_event.event_type.split('.').first)

    last_attempt_id = @webhook_event.webhook_attempts.maximum(:id)

    WebhookUrls::EVENT_TYPE_TO_JOB_CLASS[@webhook_event.event_type].perform_async(
      id_key => @webhook_event.record_id,
      'webhook_url_id' => @webhook_event.webhook_url_id,
      'event_uuid' => @webhook_event.uuid,
      'attempt' => SendWebhookRequest::MANUAL_ATTEMPT,
      'last_status' => 0
    )

    render turbo_stream: [
      turbo_stream.after(
        params[:button_id],
        helpers.tag.submit_form(
          helpers.button_to('', refresh_settings_webhook_event_path(@webhook_url.id, @webhook_event.uuid),
                            params: { last_attempt_id: }),
          class: 'hidden', data: { interval: 3_000 }
        )
      )
    ]
  end

  def refresh
    return head :ok if @webhook_event.webhook_attempts.maximum(:id) == params[:last_attempt_id].to_i

    render turbo_stream: [
      turbo_stream.replace(helpers.dom_id(@webhook_event),
                           partial: 'event_row',
                           locals: { with_status: true, webhook_url: @webhook_url, webhook_event: @webhook_event }),
      turbo_stream.replace(helpers.dom_id(@webhook_event, :drawer_events),
                           partial: 'drawer_events',
                           locals: { webhook_url: @webhook_url, webhook_event: @webhook_event })
    ]
  end

  private

  def load_webhook_event
    @webhook_event = @webhook_url.webhook_events.find_by!(uuid: params[:id])
  end
end

app/views/webhook_events/_drawer_events.html.erb
<div id="<%= dom_id(webhook_event, :drawer_events) %>">
  <ol class="relative border-s border-base-300 space-y-6 ml-3">
    <% webhook_attempts = webhook_event.webhook_attempts.sort_by { |e| -e.id } %>
    <% if webhook_event.status == 'error' %>
      <% last_attempt = webhook_attempts.select { |e| e.attempt < SendWebhookRequest::MANUAL_ATTEMPT }.max_by(&:attempt) %>
      <% if webhook_event.webhook_attempts.none?(&:success?) && last_attempt.attempt <= 10 %>
        <li class="ml-7">
          <span class="btn btn-outline btn-xs btn-circle pointer-events-none absolute justify-center border-base-content-/60 text-base-content/60 bg-base-100" style="left: -12px;">
            <%= svg_icon('clock', class: 'w-4 h-4 shrink-0') %>
          </span>
          <p class="leading-none text-base-content/90 pt-1">
            <%= t('next_attempt_in_time_in_words', time_in_words: distance_of_time_in_words(Time.current, last_attempt.created_at + (2**last_attempt.attempt).minutes)) %>
          </p>
        </li>
      <% end %>
    <% end %>
    <% if webhook_attempts.present? %>
      <% webhook_attempts.each do |webhook_attempt| %>
        <li class="ml-7">
          <span class="btn btn-outline btn-xs btn-circle pointer-events-none absolute justify-center <%= webhook_attempt.success? ? 'btn-success bg-lime-50' : 'btn-error bg-red-50' %>" style="left: -12px;">
            <%= svg_icon(webhook_attempt.success? ? 'check' : 'x', class: 'w-4 h-4 shrink-0') %>
          </span>
          <p class="leading-none text-sm text-base-content/60 pt-1">
            <%= l(webhook_attempt.created_at.in_time_zone(current_account.timezone), format: :long, locale: current_account.locale) %>
          </p>
          <div class="mt-2">
            <p class="text-sm font-bold text-base-content/80">
              <span><%= Rack::Utils::HTTP_STATUS_CODES[webhook_attempt.response_status_code] %></span>
              <% if webhook_attempt.response_status_code.positive? %>
                <span>(<%= webhook_attempt.response_status_code %>)</span>
              <% end %>
            </p>
            <% unless webhook_attempt.success? %>
              <p class="text-sm text-base-content/80 mt-1">
                <%= webhook_attempt.response_body.presence || Rack::Utils::HTTP_STATUS_CODES[webhook_attempt.response_status_code] %>
              </p>
            <% end %>
          </div>
        </li>
      <% end %>
    <% else %>
      <li class="ml-7">
        <span class="btn btn-outline btn-xs btn-circle pointer-events-none absolute justify-center btn-info bg-blue-50" style="left: -12px;">
          <%= svg_icon('clock', class: 'w-4 h-4 shrink-0') %>
        </span>
        <p class="leading-none text-base-content/60 pt-1">
          <%= l(webhook_event.created_at.in_time_zone(current_account.timezone), format: :long, locale: current_account.locale) %>
        </p>
      </li>
    <% end %>
  </ol>
  <% unless webhook_event.status == 'pending' %>
    <div class="absolute right-4 top-3">
      <%= button_to button_title(title: t('resend'), disabled_with: t('awaiting'), icon: svg_icon('rotate', class: 'w-4 h-4'), icon_disabled: svg_icon('loader', class: 'w-4 h-4 animate-spin')), resend_settings_webhook_event_path(webhook_url.id, webhook_event.uuid), form: { id: button_uuid = SecureRandom.uuid }, params: { button_id: button_uuid }, class: 'btn btn-neutral btn-sm text-white', method: :post, onclick: '[this.form.requestSubmit(), this.disabled = true]' %>
    </div>
  <% end %>
</div>

app/views/webhook_events/_event_row.html.erb
<div id="<%= dom_id(webhook_event) %>" class="group relative hover:cursor-pointer hover:bg-base-200">
  <a href="<%= settings_webhook_event_path(webhook_url.id, webhook_event.uuid) %>" data-turbo-frame="drawer" class="top-0 bottom-0 left-0 right-0 absolute"></a>
  <div class="min-h-12 flex flex-col md:flex-row md:items-center md:justify-between gap-2 px-3 py-2">
    <div class="flex items-center gap-4">
      <% if webhook_event.status == 'success' %>
        <div class="btn btn-outline btn-xs btn-success bg-lime-50 gap-1">
          <%= svg_icon('check', class: 'w-4 h-4 shrink-0 stroke-2') %>
          <%= webhook_event.webhook_attempts.max_by(&:id)&.response_status_code if local_assigns[:with_status] %>
        </div>
      <% elsif webhook_event.status == 'pending' %>
        <div class="btn btn-outline btn-xs btn-info bg-blue-50 gap-1">
          <%= svg_icon('clock', class: 'w-4 h-4 shrink-0 stroke-2') %>
          <%= webhook_event.webhook_attempts.max_by(&:id)&.response_status_code if local_assigns[:with_status] %>
        </div>
      <% elsif webhook_event.status == 'error' %>
        <div class="btn btn-outline btn-xs btn-error bg-red-50 gap-1">
          <%= svg_icon('x', class: 'w-4 h-4 shrink-0') %>
          <%= webhook_event.webhook_attempts.max_by(&:id)&.response_status_code if local_assigns[:with_status] %>
        </div>
      <% end %>
      <div><%= webhook_event.event_type %></div>
    </div>
    <div class="flex items-center gap-3">
      <%= button_to button_title(title: t('resend'), disabled_with: t('awaiting'), icon: svg_icon('rotate', class: 'w-4 h-4'), icon_disabled: svg_icon('loader', class: 'w-4 h-4 animate-spin')), resend_settings_webhook_event_path(webhook_url.id, webhook_event.uuid), form: { id: button_uuid = SecureRandom.uuid }, params: { button_id: button_uuid }, class: 'btn btn-neutral btn-xs h-2 text-white relative z-[1] hidden md:group-hover:inline-block', data: { turbo_frame: :drawer }, method: :post, onclick: "[this.form.requestSubmit(), this.disabled = true, this.classList.remove('hidden')]" %>
      <span><%= l(webhook_event.created_at, locale: current_account.locale, format: :short) %></span>
    </div>
  </div>
</div>

app/views/webhook_events/show.html.erb
<%= render 'shared/turbo_drawer', title: @webhook_event.event_type, close_after_submit: false do %>
  <div class="relative px-4 py-4">
    <%= render 'drawer_events', webhook_url: @webhook_url, webhook_event: @webhook_event %>
    <% if @data %>
      <div class="mockup-code overflow-hidden relative pb-0 mt-6">
        <% response = JSON.pretty_generate({ event_type: @webhook_event.event_type, timestamp: @webhook_event.created_at.as_json, data: @data }) %>
        <span class="top-0 right-0 absolute">
          <%= render 'shared/clipboard_copy', icon: 'copy', text: response, class: 'btn btn-ghost text-white', icon_class: 'w-6 h-6 text-white', copy_title: t('copy'), copied_title: t('copied') %>
        </span>
        <pre class="before:!m-0 pl-4 pb-4"><code class="overflow-hidden text-sm w-full"><%== HighlightCode.call(response, 'JSON', theme: 'base16.dark') %></code></pre>
      </div>
    <% end %>
  </div>
<% end %>